// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgbhGTdczQ-mVpbxARiv_ZWR-ib7AFRI',
    appId: '1:1042809810856:web:04135233f87c3328ad379d',
    messagingSenderId: '1042809810856',
    projectId: 'smart-product-recommender-fyp',
    authDomain: 'smart-product-recommender-fyp.firebaseapp.com',
    databaseURL: 'https://smart-product-recommender-fyp-default-rtdb.firebaseio.com',
    storageBucket: 'smart-product-recommender-fyp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGGCwDAIfq9HJBGDtDoB3sCKw5_KxaPW4',
    appId: '1:1042809810856:android:6f8190cafe7d7612ad379d',
    messagingSenderId: '1042809810856',
    projectId: 'smart-product-recommender-fyp',
    databaseURL: 'https://smart-product-recommender-fyp-default-rtdb.firebaseio.com',
    storageBucket: 'smart-product-recommender-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBPS2v9sark7tiNuBCYyGBAIiujPvBic',
    appId: '1:1042809810856:ios:866acde73738ddd7ad379d',
    messagingSenderId: '1042809810856',
    projectId: 'smart-product-recommender-fyp',
    databaseURL: 'https://smart-product-recommender-fyp-default-rtdb.firebaseio.com',
    storageBucket: 'smart-product-recommender-fyp.firebasestorage.app',
    iosClientId: '1042809810856-i7krhmrkbd6cagf2l8p85g19cl444hrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
